CREATE TABLE `hwreports` (
  `uid` int(5) NOT NULL auto_increment,
  `filename` varchar(64) NOT NULL default '',
  `gamename` varchar(32) NOT NULL default '',
  `gameid` varchar(16) NOT NULL default '',
  `clienttag` varchar(8) NOT NULL default '',
  `gametype` varchar(16) NOT NULL default '',
  `gameoption` varchar(16) NOT NULL default '',
  `gamecreated` varchar(64) NOT NULL default '',
  `gamestarted` varchar(64) NOT NULL default '',
  `gameended` int(10) NOT NULL,
  `map` varchar(64) NOT NULL default '',
  `mapauth` varchar(32) NOT NULL default '',
  `mapsize` varchar(16) NOT NULL default '',
  `tileset` varchar(16) NOT NULL default '',
  `joins` int(2) NOT NULL default '0',
  `maxplayers` int(2) NOT NULL default '0',
  `host` varchar(16) NOT NULL,
  `port` int(5) NOT NULL default '0',
  `p1name` varchar(32) NOT NULL default '',
  `p1result` varchar(8) NOT NULL default '',
  `p1rating` int(5) NOT NULL default '0',
  `p1num` varchar(8) NOT NULL default '',
  `p1prob` varchar(8) NOT NULL default '',
  `p1k` int(3) NOT NULL default '0',
  `p1adj` varchar(8) NOT NULL default '',
  `p1race` varchar(8) NOT NULL default '',
  `p1time` int(16) NOT NULL default '0',
  `p1scoreoverall` int(8) NOT NULL default '0',
  `p1units` int(8) NOT NULL default '0',
  `p1structures` int(8) NOT NULL default '0',
  `p1resources` int(8) NOT NULL default '0',
  `p1unitsscore` int(8) NOT NULL default '0',
  `p1produced` int(8) NOT NULL default '0',
  `p1killed` int(8) NOT NULL default '0',
  `p1lostu` int(8) NOT NULL default '0',
  `p1structuresscore` int(8) NOT NULL default '0',
  `p1constructed` int(8) NOT NULL default '0',
  `p1razed` int(8) NOT NULL default '0',
  `p1losts` int(8) NOT NULL default '0',
  `p1resourcesscore` int(8) NOT NULL default '0',
  `p1gas` int(8) NOT NULL default '0',
  `p1minerals` int(8) NOT NULL default '0',
  `p1spent` int(8) NOT NULL default '0',
  `p2name` varchar(32) NOT NULL default '',
  `p2result` varchar(8) NOT NULL default '',
  `p2rating` int(5) NOT NULL default '0',
  `p2num` varchar(8) NOT NULL default '',
  `p2prob` varchar(8) NOT NULL default '',
  `p2k` int(3) NOT NULL default '0',
  `p2adj` varchar(8) NOT NULL default '',
  `p2race` varchar(8) NOT NULL default '',
  `p2time` int(16) NOT NULL default '0',
  `p2scoreoverall` int(8) NOT NULL default '0',
  `p2units` int(8) NOT NULL default '0',
  `p2structures` int(8) NOT NULL default '0',
  `p2resources` int(8) NOT NULL default '0',
  `p2unitsscore` int(8) NOT NULL default '0',
  `p2produced` int(8) NOT NULL default '0',
  `p2killed` int(8) NOT NULL default '0',
  `p2lostu` int(8) NOT NULL default '0',
  `p2structuresscore` int(8) NOT NULL default '0',
  `p2constructed` int(8) NOT NULL default '0',
  `p2razed` int(8) NOT NULL default '0',
  `p2losts` int(8) NOT NULL default '0',
  `p2resourcesscore` int(8) NOT NULL default '0',
  `p2gas` int(8) NOT NULL default '0',
  `p2minerals` int(8) NOT NULL default '0',
  `p2spent` int(8) NOT NULL default '0',
  `p1normalrecord` varchar(32) NOT NULL default '',
  `p1ladderrecord` varchar(32) NOT NULL default '',
  `p2normalrecord` varchar(32) NOT NULL default '',
  `p2ladderrecord` varchar(32) NOT NULL default '',
  `gameduration` int(8) NOT NULL default '0',
  PRIMARY KEY  (`uid`),
  KEY `host` (`host`),
  KEY `gameended` (`gameended`),
  KEY `clienttag` (`clienttag`),
  KEY `p1name` (`p1name`,`p2name`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251 AUTO_INCREMENT=482288;